### ISSUE TITLE
module 2.3 Assignment

### ISSUE THREAD

**Issue by Or0ch1** [DSCKabarak/Github-Training#104]
![error](https://user-images.githubusercontent.com/54472219/100522891-2dafad80-31bd-11eb-885e-d09fade41f9b.png)
![edit module2](https://user-images.githubusercontent.com/54472219/100522827-d8739c00-31bc-11eb-931b-6bca308bc887.png)
![changes and terminal push](https://user-images.githubusercontent.com/54472219/100522700-df4ddf00-31bb-11eb-9c3a-082d934a4d7f.png)
![termialpushfinal](https://user-images.githubusercontent.com/54472219/100522708-e5dc5680-31bb-11eb-8beb-cdcfd21b11ba.png)
![merge2](https://user-images.githubusercontent.com/54472219/100522772-7450d800-31bc-11eb-8fb2-c838f52126ae.png)

**Comment by kevinbanister** [comment]
Awesome!
