### ISSUE TITLE
Module 1.1 Assignment

### ISSUE THREAD

**Issue by BrandyKip** [DSCKabarak/Github-Training#14]
Given what you have learned about Git, why would you want to use it?
I'd  love to advance in my code knowledge and get to know what's going on in the development world.

**Comment by kosty-dev** [comment]
I would want to keep track of the changes I make on my code and go back when necessary.

**Comment by kevinbanister** [comment]
Awesome @BrandyKip . @kosty-dev create a new issue with you as the author.
