### ISSUE TITLE
git bash

### ISSUE THREAD

**Issue by timngeno** [DSCKabarak/Github-Training#15]
![Screenshot (286)](https://user-images.githubusercontent.com/55910769/100059100-91437f00-2e3b-11eb-872d-a030ad4345f7.png)
![Screenshot (287)](https://user-images.githubusercontent.com/55910769/100059136-a1f3f500-2e3b-11eb-8c90-5c9c24b14435.png)

**Comment by kevinbanister** [comment]
Good work!
