### ISSUE TITLE
Module 1.1 Assingment

### ISSUE THREAD

**Issue by lazarusmugo** [DSCKabarak/Github-Training#16]
Given what you have learned about Git, why would you want to use it?

Git enables creation of repositories and stores snapshots of the work done at a user defined intervals. This will to reset to a previous version of work done incase there is accidental deletion or breaking of code by changes a user can make.
Other than that Git is a distributed version control system , which is convenient as it enables one to store copies of a repository to every developer's personal computer on ones team, and thus enable recovery incase any of the errors as described above should occur. GitHub also offers storage of repositories.

**Comment by kevinbanister** [comment]
Good work, Git is super essential for managing multiple repositories and keeping a log of all the changes made.
