### ISSUE TITLE
module 1.2 assigment

### ISSUE THREAD

**Issue by Rose-gitungo** [DSCKabarak/Github-Training#22]
![git 1 2  1](https://user-images.githubusercontent.com/52779154/100088937-f9a55700-2e61-11eb-86c4-63aa2629a016.png)

![git 1 2](https://user-images.githubusercontent.com/52779154/100088659-86034a00-2e61-11eb-97e8-c9d8018070ed.png)

**Comment by kevinbanister** [comment]
Good work.

On your first repository, you initialized a whole directory which is a mistake because you are tracking all the folders in that directory.

**Comment by Rose-gitungo** [comment]
oh saw it yes it was a mistake will it cause problems ahead?

**Comment by kevinbanister** [comment]
It just means git will be tracking all the files on your pc. Find the .git file and delete it to stop the tracking.

**Comment by Rose-gitungo** [comment]
okay oky thank you
