### ISSUE TITLE
Module 1.2 Assignment

### ISSUE THREAD

**Issue by Jess2001** [DSCKabarak/Github-Training#25]
![Screenshot (10)](https://user-images.githubusercontent.com/67761227/100109056-84934b00-2e7c-11eb-8082-525bc8cadba4.png)
![Screenshot (11)](https://user-images.githubusercontent.com/67761227/100109062-865d0e80-2e7c-11eb-8e52-6317a83a652f.png)
![Screenshot (12)](https://user-images.githubusercontent.com/67761227/100109064-865d0e80-2e7c-11eb-8394-5dc4fa098331.png)
![Screenshot (14)](https://user-images.githubusercontent.com/67761227/100109069-86f5a500-2e7c-11eb-8460-fa52ab05db4f.png)
![Screenshot (13)](https://user-images.githubusercontent.com/67761227/100109089-8bba5900-2e7c-11eb-8497-5838b2c258fd.png)

**Comment by kevinbanister** [comment]
Hi, you initialized git in the entire directory instead of the Github Training Folder. Please fix that error.
