### ISSUE TITLE
Given what you have learned about Git, why would you want to use it?

### ISSUE THREAD

**Issue by mercycheeky** [DSCKabarak/Github-Training#36]
- Git is a version control system that enables a person to maintain multiple files overtime.

- It enables a developer to save drafts and save file changes. 

- It accesses the historical records for his files and even the previous contents of his work.

- Git's distributed version control can copy every of a developer's files to all the other computers of his/her fellow teammates, so one can acquire work he has lost.

- Git commands also synchronise changes in these computers.

**Comment by kevinbanister** [comment]
Good work!
