### ISSUE TITLE
MODULE 1.2 ASSIGNMENT

### ISSUE THREAD

**Issue by Jess2001** [DSCKabarak/Github-Training#44]
![Screenshot (19)](https://user-images.githubusercontent.com/67761227/100214857-69c6e200-2f21-11eb-8013-b81ce08b9246.png)
![Screenshot (20)](https://user-images.githubusercontent.com/67761227/100214863-6c293c00-2f21-11eb-9ff4-945af2c5a358.png)

**Comment by kevinbanister** [comment]
Good work!
