### ISSUE TITLE
Model 1.2 Assignment

### ISSUE THREAD

**Issue by Maishmike** [DSCKabarak/Github-Training#47]
![MINGW64__c_Users_User_Project1 11_25_2020 2_44_44 PM](https://user-images.githubusercontent.com/74899947/100223814-0a6ecf00-2f2d-11eb-81d8-7709f218aadb.png)
![Select MINGW64__c_Users_User_Project1 11_25_2020 2_45_28 PM](https://user-images.githubusercontent.com/74899947/100223818-0c389280-2f2d-11eb-869d-8a944a1b4008.png)

**Comment by kevinbanister** [comment]
Nice work!
