### ISSUE TITLE
Module 2.2 assignment

### ISSUE THREAD

**Issue by Or0ch1** [DSCKabarak/Github-Training#53]
![merge with  master](https://user-images.githubusercontent.com/54472219/100268126-9a306f80-2f65-11eb-84b3-8648db66ade4.png)
![git pull](https://user-images.githubusercontent.com/54472219/100268139-9e5c8d00-2f65-11eb-9bab-1f72a8338335.png)

**Comment by kevinbanister** [comment]
Good work!
