### ISSUE TITLE
Module assignment 1.4

### ISSUE THREAD

**Issue by Maishmike** [DSCKabarak/Github-Training#59]
![Github-Training_Module 1 3 Assignment md at master · Maishmike_Github-Training — Mozilla Firefox 11_26_2020 11_12_53 AM](https://user-images.githubusercontent.com/74899947/100324522-6e9a9d00-2fd8-11eb-928a-bee05dfc466f.png)

**Comment by kevinbanister** [comment]
Now you understand more on branching, kudos!
