### ISSUE TITLE
Module Assignment 2.4

### ISSUE THREAD

**Issue by Maishmike** [DSCKabarak/Github-Training#82]
![MINGW64__c_Users_User_MergeConflict 11_26_2020 7_18_32 PM](https://user-images.githubusercontent.com/74899947/100373933-93b0ff00-301c-11eb-9630-f23776f597a2.png)
![MINGW64__c_Users_User_MergeConflict 11_26_2020 7_18_39 PM](https://user-images.githubusercontent.com/74899947/100373937-957ac280-301c-11eb-9c9a-783c39310c9e.png)

**Comment by kevinbanister** [comment]
Nice work!
